### ISSUE TITLE
Support operator to inject sidecar?

### ISSUE THREAD

**Issue by caibirdme** [vectordotdev/helm-charts#231] opened 2022-07-25 03:35 UTC
Do we have any plan to support k8s operator to inject vector as a sidecar container?
We want to widely deploy vector in our system, but here's the problem we met:
1. we don't use stdout/stderr to log, we use file
2. It's nearly an impossible task to write a series new SDKs(go java rust cpp) for all service that can buffer logs and send data to the centralized vector in batch
3. Even we manage to write these sdks, it'd be a very long term to have different teams to use these new sdk in their production

Maybe the most non-intrusive and easiest way is that:
1. people still write log to local files
2. people tell "log system" where their log files are and the url of the centralized vector service by ENVIRONMENT, something like:
```yaml
env:
  - key: LOG_FILE
    value: /a/b-*.log;/c/d.log
  - key: LOG_SERVICE
    value: example.com:6788
```
3. Operator inject vector container as a sidecar for every pod, and vector instance bootstrap with these env params

 So, as the infra team, we just need to install a vector operator on k8s cluster. And as for other business teams, they just need to do no more than 4 lines change for their deployment.yaml file.

**Comment by spencergilbert** [comment] 2022-07-25 13:42
At this time it's not on our roadmap, but it has been discussed again recently.

Closing as a duplicate of: https://github.com/vectordotdev/vector/issues/768

**Closed by spencergilbert** 2022-07-25 13:42 UTC
